obj-y	+= isp-drv.o
obj-y	+= csi.o
obj-y	+= mscaler.o
obj-y	+= vic.o
obj-y	+= isp.o
obj-y	+= sensor.o
obj-y	+= isp-video.o

ccflags-y += -I$(srctree)/drivers/media/platform/ingenic-isp/isp-core/inc
obj-y	+= isp-core/
