#!/bin/sh
#
# Start mdev....
#

case "$1" in
  start)
	mount_ubifs.sh userdata /usr/data/
    reboot_mon.sh &
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
