
ccflags-y += -Idrivers/media/platform/ingenic-vcodec/felix/libh264/
ccflags-y += -Idrivers/media/platform/ingenic-vcodec/felix/libh264/include

obj-y += felix_ops.o
obj-y += felix_drv.o

obj-y += libh264/



