## X1000 Supported Boards
obj-$(CONFIG_SND_ASOC_INGENIC_X1000_BOARD) += x1000-board.o

## X2000 Supported Boards
obj-$(CONFIG_SND_ASOC_INGENIC_SEAL) += seal.o

## X2000 v12 Supported Boards
obj-$(CONFIG_SND_ASOC_INGENIC_ZEBRA) += zebra.o

obj-$(CONFIG_SND_ASOC_INGENIC_ZEBRA_DMIC_ICDC) += zebra_dmic_icdc.o

obj-$(CONFIG_SND_ASOC_INGENIC_HALLEY5_V20) += halley5_v20.o
